### ISSUE TITLE
Add a new feature to generate krakend json from swagger json

### ISSUE THREAD

**Issue by prakkarp** [krakendio/krakendesigner#94]
Add functionality to the krakenD designer to generate the endpoints from the swagger json. This would reduce the time taken to generate the krakend json using the designer. 
Most of the cloud API gateway like AWS api gateway, apigee and others offer this functionality. So this is something very useful to have.

**Comment by alombarte** [comment]
Moved the issue to the krakend designer as it is the place where it could be implemented

**Comment by giosueDelgado** [comment]
Is very important to have this feature because on large project that use swagger / openapi if is available the import feature is very fast to migrate and use this API Gateway.

**Comment by milanjaros** [comment]
As @alombarte described generating KrakenD JSON from swagger is "**5 minutes of work**" task. The devil is in the details. @giosueDelgado, the "import feature" you think about could be totally different from the "import feature" (transition) we are going to follow on our project. 
For example, we started to use KrakenD more than a year ago and we had a different approach than we have today. We thought we will use a lot of KrakendD features (like data manipulation, circuit breaker, caching, etc.) but we ended up with just no-op proxy. So, the use case changes from "intensive manual gateway configuration" to just "exposing private APIs to public API". As you can see, the motivation and needs could differ.

### Custom gateway configuration format
Maybe it could be useful for someone (just as an inspiration) if I share a python snippet that I created as a Proof of Concept to just "simplify manual gateway configuration" for a team. Even we use templating we have like 25 *.tmpl files with the sum of 6000 lines of configuration. I wanted to try to shrink the Endpoint configuration to the minimum, so we would have just `template.yml`, something like:

```yaml
/inbox:
  GET:
    - host: [ "http://inbox.user" ]
/profile/images:
  GET:
    - url_pattern: /images
      host: [ "http://profiles.user" ]
  PUT:
    - url_pattern: /images
      host: [ "http://profiles.user" ]
# The most complicated configuration would look like
/contracts/upload:
  POST:
    - url_pattern: /upload
      host: [ "http://contracts.files" ]
      endpoint:
        headers_to_pass: [ "{{ .default_headers }}", "Content-Encoding" ]
        querystring_params: [ "*" ]
```
As you can see, the structure is inspired by OpenAPI (I wanted to make it simple for both mobile and backend developers who are used to writing OAS) but on the other hand, it is a "new proprietary format" because as you know OpenAPI does not contain such things as `url_pattern` or `host` and you can't just extend it if you use code generation and validation tools. 
My proposal was to copy the path to `url_pattern` and take the rest from `defaults.json` which could look like:
```json
{
    "extra_config": "{{ marshal .jwt_token_validator }}",
    "output_encoding": "no-op",
    "headers_to_pass": [ "{{ .default_headers }}" ],
    "backend": [
        {
            "host": ["{{ .host_users }}"],
            "encoding": "no-op"
        }
    ]
}
```
Finally, there is a script where you can enjoy precisely "chosen" Christmas tree design pattern.🎄😉 I hope that there are just enough comments. It is also fair to mention, we do not use it in production because our motivation has changed.
```python
import oyaml as yaml
import json
import sys, copy

# Load files
if(len(sys.argv) != 3):
    exit("usage: generate_configuration.py <template.yml> <defaults.json>")
template = open(sys.argv[1])
defaults = open(sys.argv[2])
urls = yaml.safe_load(template)
default = json.load(defaults)

# set item to array and extend it if needed
def ensure_array_has_item(variable, item, index):
    if item not in variable:
        variable[item] = []
    if len(variable[item]) <= index:
        variable[item].append({})

out = []
# Append all endpoints from defined URLs
for url in urls:
    endpoint = {}
    # Load defaults
    for prop in default:
        endpoint[prop] = copy.deepcopy(default[prop])
    # Update endpoints from defined HTTP methods and their items
    methods = urls[url]
    for method in methods:
        # This does he openapi.yaml to krakend.json transformation
        endpoint["endpoint"] = url
        endpoint["method"] = method
        items = methods[method]
        # Copy config of endpoins
        for i, item in enumerate(items):
            ensure_array_has_item(endpoint, "backend", i)
            endpoint["backend"][i]["method"] = method
            for prop in item:
                # Set all properties of a HTTP method
                if prop != "endpoint":
                    endpoint["backend"][i][prop] = item[prop]
                else:
                    # Set endpoint properties to (parent) endpoint
                    for endpoint_prop in item[prop]:
                        endpoint[endpoint_prop] = item[prop][endpoint_prop]
            # Set URL from (parent) endpoint to endpoint backend if not set
            if "url_pattern" not in endpoint["backend"][i]:
                endpoint["backend"][i]["url_pattern"] = url

    out.append(endpoint)

print(json.dumps(out, indent=4))
```

**Comment by okhuz** [comment]
I am writing a piece of code that converts OpenAPI definition to krakend.json for our APIs. Our microservices serve their API definition internally so every update to API definition will restart the gateways as well and gateway will pick up new definition. It shows a lot of promise though, still in PoC mode though.

**Comment by alombarte** [comment]
This functionality exists already in the Enterprise edition, and allows generating a KrakenD configuration by passing an openapi spec:
```
$krakend generate from openapi -c ~/Downloads/openapi.yaml -o krakend.json
```
https://www.krakend.io/docs/enterprise/developer/openapi/

From our side I don't see this feature ported to the designer any time soon, but if there is any contributor willing to do it please send a PR.
